// File generated by FlutterFire CLI.
//
// HAND-PATCHED 2026-08-06 after the bundle ID moved to app.studease.mobile. A
// `flutterfire configure` run updated GoogleService-Info.plist and google-services.json
// but left this file untouched, and this file is the one that wins — main.dart passes it
// explicitly to Firebase.initializeApp, which overrides the native config entirely. The
// two appIds and iosBundleId below were copied from those regenerated config files.
//
// If a later `flutterfire configure` overwrites this file, that is the correct outcome —
// check the values still match the config files rather than restoring this comment.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCUaMjte8qe8iCO0KLW4o7TsvXxVkMq4',
    appId: '1:219277229074:android:d79de065c013d51275accb',
    messagingSenderId: '219277229074',
    projectId: 'swift-study-app',
    storageBucket: 'swift-study-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAVoRmaaitzvYv7m_VXeAY_5azmy1qn9s',
    appId: '1:219277229074:ios:d498ca675f4be9a675accb',
    messagingSenderId: '219277229074',
    projectId: 'swift-study-app',
    storageBucket: 'swift-study-app.firebasestorage.app',
    iosBundleId: 'app.studease.mobile',
  );
}
