// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using study_spot_backend;

#nullable disable

namespace study_spot_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250712035918_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("study_spot_backend.StudySpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("CoffeeQuality")
                        .HasColumnType("integer");

                    b.Property<string>("DrinkOrder")
                        .HasColumnType("text");

                    b.Property<string>("ExtraNotes")
                        .HasColumnType("text");

                    b.Property<string>("GeneralPrice")
                        .HasColumnType("text");

                    b.Property<bool>("HasCharging")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("OpenUntil")
                        .HasColumnType("interval");

                    b.Property<int>("Seating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudySpots");
                });
#pragma warning restore 612, 618
        }
    }
}
