// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using study_spot_backend;

#nullable disable

namespace study_spot_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831195604_AllowHyphenatedLabelSlugs")]
    partial class AllowHyphenatedLabelSlugs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabelSpotEntry", b =>
                {
                    b.Property<Guid>("EntriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("entries_id");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.HasKey("EntriesId", "TagsId")
                        .HasName("pk_spot_entry_tags");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_spot_entry_tags_tags_id");

                    b.ToTable("spot_entry_tags", (string)null);
                });

            modelBuilder.Entity("study_spot_backend.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Polarity")
                        .HasColumnType("text")
                        .HasColumnName("polarity");

                    b.Property<Guid?>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_labels_approved_by");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("ix_labels_requested_by");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_labels_slug");

                    b.ToTable("labels", null, t =>
                        {
                            t.HasCheckConstraint("ck_labels_polarity_valid", "polarity IS NULL OR polarity IN ('positive', 'negative')");

                            t.HasCheckConstraint("ck_labels_slug_format", "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(slug) BETWEEN 2 AND 30");

                            t.HasCheckConstraint("ck_labels_status_valid", "status IN ('pending', 'approved', 'rejected')");
                        });
                });

            modelBuilder.Entity("study_spot_backend.Models.Spot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<decimal?>("AvgCoffee")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("avg_coffee");

                    b.Property<decimal?>("AvgNoise")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("avg_noise");

                    b.Property<decimal?>("AvgOutlets")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("avg_outlets");

                    b.Property<decimal?>("AvgScore")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("avg_score");

                    b.Property<decimal?>("AvgSeating")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("avg_seating");

                    b.Property<decimal?>("AvgTableSize")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("avg_table_size");

                    b.Property<decimal?>("AvgWifi")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("avg_wifi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<string>("FormattedAddress")
                        .HasColumnType("text")
                        .HasColumnName("formatted_address");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("text")
                        .HasColumnName("google_place_id");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("PlacesSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("places_synced_at");

                    b.Property<short?>("PriceLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("price_level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("utc_offset_minutes");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("visit_count");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_spots");

                    b.HasIndex("AddedBy")
                        .HasDatabaseName("ix_spots_added_by");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_spots_google_place_id")
                        .HasFilter("google_place_id IS NOT NULL");

                    b.ToTable("spots", null, t =>
                        {
                            t.HasCheckConstraint("ck_spots_lat_range", "latitude IS NULL OR latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_spots_lng_range", "longitude IS NULL OR longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("ck_spots_price_range", "price_level IS NULL OR price_level BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("study_spot_backend.Models.SpotEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Coffee")
                        .HasColumnType("smallint")
                        .HasColumnName("coffee");

                    b.Property<string>("CoffeeOrder")
                        .HasColumnType("text")
                        .HasColumnName("coffee_order");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("GroupStudy")
                        .HasColumnType("boolean")
                        .HasColumnName("group_study");

                    b.Property<short>("Noise")
                        .HasColumnType("smallint")
                        .HasColumnName("noise");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("Outlets")
                        .HasColumnType("smallint")
                        .HasColumnName("outlets");

                    b.Property<decimal>("Score")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("score")
                        .HasComputedColumnSql("round((wifi + noise + outlets + seating + coffee) * 0.4, 1)", true);

                    b.Property<short>("Seating")
                        .HasColumnType("smallint")
                        .HasColumnName("seating");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<short>("TableSize")
                        .HasColumnType("smallint")
                        .HasColumnName("table_size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visibility");

                    b.Property<short>("Wifi")
                        .HasColumnType("smallint")
                        .HasColumnName("wifi");

                    b.HasKey("Id")
                        .HasName("pk_spot_entries");

                    b.HasIndex("SpotId")
                        .HasDatabaseName("ix_spot_entries_spot_id");

                    b.HasIndex("UserId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_spot_entries_user_id_score");

                    b.HasIndex("UserId", "SpotId")
                        .IsUnique()
                        .HasDatabaseName("ix_spot_entries_user_id_spot_id");

                    b.ToTable("spot_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_spot_entries_coffee_range", "coffee BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_spot_entries_noise_range", "noise BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_spot_entries_outlets_range", "outlets BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_spot_entries_seating_range", "seating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_spot_entries_table_size_range", "table_size BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_spot_entries_visibility_valid", "visibility IN ('public', 'followers', 'private')");

                            t.HasCheckConstraint("ck_spot_entries_wifi_range", "wifi BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("study_spot_backend.Models.SpotTagCount", b =>
                {
                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.HasKey("SpotId", "LabelId")
                        .HasName("pk_spot_tag_counts");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_spot_tag_counts_label_id");

                    b.ToTable("spot_tag_counts", (string)null);
                });

            modelBuilder.Entity("study_spot_backend.Models.SpotVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DrinkOrder")
                        .HasColumnType("text")
                        .HasColumnName("drink_order");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid")
                        .HasColumnName("spot_id");

                    b.Property<string>("Studied")
                        .HasColumnType("text")
                        .HasColumnName("studied");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at");

                    b.HasKey("Id")
                        .HasName("pk_spot_visits");

                    b.HasIndex("UserId", "VisitedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_spot_visits_user_id_visited_at");

                    b.HasIndex("SpotId", "UserId", "VisitedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_spot_visits_spot_id_user_id_visited_at");

                    b.ToTable("spot_visits", (string)null);
                });

            modelBuilder.Entity("study_spot_backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_provider");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_subject");

                    b.Property<bool>("AvatarBackgroundTint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("avatar_background_tint");

                    b.Property<string>("AvatarColor")
                        .HasColumnType("text")
                        .HasColumnName("avatar_color");

                    b.Property<string>("AvatarId")
                        .HasColumnType("text")
                        .HasColumnName("avatar_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("handle");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_guest");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_users_handle");

                    b.HasIndex("AuthProvider", "AuthSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth_provider_auth_subject");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_avatar_color_valid", "avatar_color IN ('terracotta', 'slate', 'sage', 'plum', 'cranberry', 'mustard', 'forest', 'denim') OR avatar_color IS NULL");

                            t.HasCheckConstraint("ck_users_avatar_id_valid", "avatar_id IN ('cafe_01', 'cafe_02', 'cafe_03', 'cafe_04', 'cafe_05', 'cafe_06', 'cafe_07', 'cafe_08', 'cafe_09', 'cafe_10') OR avatar_id IS NULL");

                            t.HasCheckConstraint("ck_users_handle_format", "handle ~ '^[a-z0-9_]{3,30}$'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000d5"),
                            AuthProvider = "dev",
                            AuthSubject = "local",
                            AvatarBackgroundTint = false,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Dev User",
                            Handle = "dev",
                            IsAdmin = true,
                            IsGuest = false,
                            IsPrivate = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LabelSpotEntry", b =>
                {
                    b.HasOne("study_spot_backend.Models.SpotEntry", null)
                        .WithMany()
                        .HasForeignKey("EntriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_entry_tags_spot_entries_entries_id");

                    b.HasOne("study_spot_backend.Models.Label", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_entry_tags_labels_tags_id");
                });

            modelBuilder.Entity("study_spot_backend.Models.Label", b =>
                {
                    b.HasOne("study_spot_backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_labels_users_approved_by");

                    b.HasOne("study_spot_backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_labels_users_requested_by");
                });

            modelBuilder.Entity("study_spot_backend.Models.Spot", b =>
                {
                    b.HasOne("study_spot_backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AddedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_spots_users_added_by");
                });

            modelBuilder.Entity("study_spot_backend.Models.SpotEntry", b =>
                {
                    b.HasOne("study_spot_backend.Models.Spot", "Spot")
                        .WithMany("Entries")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_entries_spots_spot_id");

                    b.HasOne("study_spot_backend.Models.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_entries_users_user_id");

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("study_spot_backend.Models.SpotTagCount", b =>
                {
                    b.HasOne("study_spot_backend.Models.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_tag_counts_labels_label_id");

                    b.HasOne("study_spot_backend.Models.Spot", "Spot")
                        .WithMany()
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_tag_counts_spots_spot_id");

                    b.Navigation("Label");

                    b.Navigation("Spot");
                });

            modelBuilder.Entity("study_spot_backend.Models.SpotVisit", b =>
                {
                    b.HasOne("study_spot_backend.Models.Spot", "Spot")
                        .WithMany()
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_visits_spots_spot_id");

                    b.HasOne("study_spot_backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spot_visits_users_user_id");

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("study_spot_backend.Models.Spot", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("study_spot_backend.Models.User", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
